apiVersion: v1
kind: Secret
metadata:
  name: myroutemap-secrets
  namespace: myroutemap
type: Opaque
data:
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  MONGODB_PASSWORD: cGFzc3dvcmQxMjM=
  CLOUDINARY_API_SECRET: Y2xvdWRpbmFyeS1hcGktc2VjcmV0
  EMAIL_PASSWORD: ZW1haWwtcGFzc3dvcmQ=